### ISSUE TITLE
Subtyping checks?

### ISSUE THREAD

**Issue by smarter** [twitter/rsc#19]
I don't see any mention of subtyping in the code or the documentation (which is otherwise very well written and detailed for such a young project, nice job!). And indeed, the following happily typechecks:
```scala
class Foo()
class Bar()

object Test {
  val x: Bar = new Foo()
}
```

Will subtyping checks be implemented in the first milestone?

**Comment by xeno-by** [comment]
Thanks for the kind words! One of the goals of Rsc is to share our experiments with everyone in the Scala community, and it makes it pretty mandatory to write design documents :)

Indeed, the checking functionality is missing from the current prototype (it's not just subtyping checks, but also method applicability checks, etc etc), and that's an intentional omission. In order to get off the ground faster, we decided to postpone this.

To quote [compiler.md](../blob/master/docs/compiler.md), "In a nutshell, we assume that underlying programs are correct, making a lot of functionality of the typer unnecessary. We are planning to implement that missing functionality in the future, but in the meanwhile we can almost immediately deliver value to our users".

I'll keep this ticket open for now, since I believe this will be a frequently asked question, but I won't be assigning it to a milestone just yet.

**Comment by xeno-by** [comment]
I've just updated [our roadmap](https://github.com/twitter/rsc/milestones), and it is unlikely that we'll be working on this ticket in the near future. 

In a nutshell, we'll first need to teach Rsc to to read SemanticDB in order to support binary dependencies, then how to write SemanticDB in order to kickstart tooling support, and only then we'll get to resume our typechecker work.

Therefore, I'll be closing this ticket with "Postponed" and will revive it (or, most likely, submit follow-up related tickets after tackling #12) when the time comes.
