### ISSUE TITLE
Benchmark NoUid vs Option[Uid]

### ISSUE THREAD

**Issue by xeno-by** [twitter/rsc#6]
Both Scalac and Dotty extensively use null objects instead of options. One of the reasons for that, which I heard from someone during my time at EPFL, is performance. Let's quantify this by trying to get rid of NoUid and replacing all Uid-typed fields with Option[Uid].

**Comment by smarter** [comment]
You could also try using https://github.com/sjrd/scala-unboxed-option :).

**Comment by xeno-by** [comment]
Lots of opportunities to explore! Thanks for the tip.

**Comment by DavidDudson** [comment]
I can second unboxed options. We use them extensively in our parsers and models where it makes sense. Memory savings and safety without too many downsides.

**Comment by xeno-by** [comment]
@DavidDudson Can you elaborate on the downsides of unboxed options?

**Comment by DavidDudson** [comment]
By definition, unboxed Options are stored as their underlying type, meaning you have to represent None in the underlying type, thus primitives are not supported. The common pattern is to treat `null` as empty, but there are other ways also depending on the type in question.

One example.... optionally storing line/column and start/stop offset data inside your language model.

If you choose to use `Opt[Int]` or even `Opt[Short]` fields it won't work due to them being primitives.
Of course `Opt[Integer]` will work, although, for clarity, I type alias `java.lang.Integer` to `BoxedInt` etc.

The alternative which we use at work uses 1 more object per ast node is to have some case class for data, which makes it a little bit simpler.


```scala
   // Simplified 
   case class Context(line: Int, offset: Int)
```

Thus `Opt[Context]` stores 1 object + 2 primitive Int's. which is great. `Option[Context]` stores 2 object refs + 2 primitive refs.

However, if you map, extracting the `line` parameter, the line is now boxed.

`someCtx.map(_.line).filter(_ % 2 == 1).map(_ + 1)`

In the above, the chain is using boxed ints, thus its memory churn is actually almost identical to using `Option`, since `Option` will not box the ints, but will create `Option` instances for every step in the chain. It can be more efficient to manually write that does not use monadic chaining. Given that short-term objects are what the JVM loves I'd benchmark heavily before saying this is a problem (As the lamdas are created also).

Although. It can also be useful to have a private field which is explicitly `null` unless set, then have the getter overridden to return `Option[Context]`. Depending on how performance critical usages of the Optional thing are and how frequently it is accessed, you can still store it without the extra object ref. But still use a regular std lib Option for interacting with it. Unboxed options will however outperform here.

```scala
   @Nullable private val _ctx = ???
   def ctx: Option[Context] = Option(_ctx)
```

At work, we use a mutable stack to build our ast... And every ast node could be an error node, thus we use unboxed options like the following....

```
 // If I were building a scalameta Defn.Val
 // note stack.pop returns an unboxed option
 for {
   rhs <- stack.pop[Term]
   decltpe <- stack.pop[scala.meta.Type]
   pats <- stack.pop[NonEmptyList[Pat]]
   mods <- stack.pop[List[Mod]]
   if (pats.forall(!_.is[Term.Name]))
 } yield Defn.Val(mods, pats, decltpe, rhs)
``` 

We then push the result back on the stack.

Unboxed options are perfect here, as if you compare memory churn of boxed vs unboxed options the differences are huge.

AFAICT unboxed options are at worst case equal to `Option` in performance and memory usage (Usually when dealing with primitives) but are almost always better.

Neither sjrd's nor any other implementation of unboxed option I've seen is complete (As far as being an exact replica of `Option` with all it's functionality). although sjrd's is probably the best starting point to implement your own. (Note: Sjrd's does not have flatmap AFAIK)

I would of course encourage you to profile, profile and profile some more, in allocations/second, GC times, throughput etc. to see whether unboxing the option is worth it for specific parts of the compiler.

**Comment by xeno-by** [comment]
After doing preliminary experimentation with the "Benchmark architectural change XXX" tickets, we found out that performance effects of many of these changes lie within the range of run-to-run variance of our current benchmark suite. This makes it hard to form an informed judgement about these changes, so we decided to postpone further experiments until we implement support for more language features and make our benchmark suite more diverse.
